### ISSUE TITLE
메인 페이지, 공부 페이지, 웹게이저 구현

### ISSUE THREAD

**Issue by JunHyeong-99** [new3seagull/SeagullsRoom#13]
## description
메인 화면 구현, 공부 페이지의 타이머를 구현, 웹게이저를 연동한다.

## Todo

메인 화면 구현
- [x]  공부 시작 버튼
- [x]  공부 시간 조회 (오늘 기록)

공부 페이지 구현
- [x] 타이머 흘러가게 시각화
- [x] stop 누르면 api 전송 후 저장

웹게이저 연동
- [x] 캘러브레이션 화면
- [x] js 추가
