### ISSUE TITLE
마이페이지 수정

### ISSUE THREAD

**Issue by dhfpswlqkd** [new3seagull/SeagullsRoom#46]
## Todo

- [x] 마이페이지-오늘 학습 시간 수정, 연속 학습 일수 삭제
- [x] 챗봇 디자인 개선
- [x] 마이페이지-툴바 이미지 오류 수정
- [x] 친구페이지, 랭킹 페이지 추가
