### ISSUE TITLE
스크린 타임 기록 구현

### ISSUE THREAD

**Issue by J-1ac** [new3seagull/SeagullsRoom#48]
## description
GPT API 결과로 받아온 분류된 스크린 타임을 사용자 별로 기록한다.

## Todo
- [x] 스크린타임 도메인 추가하기
- [x] 카테고리 추가하기 (최소 3개 지정? 최대 5개)
- [x] 지피티 request에 사용자 카테고리 추가하기
